# The URL the site will be built for
base_url = "https://docs.dinomatic.com"

# Site title
title = "DinoMatic Docs"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Render emoji
render_emoji = true

[markdown]
highlight_code = true
highlight_theme = "dracula"

[extra]
products = [
  "akurai", "spinoko", "fxt", "kemoku", "dinodds", "akurai-geo", "spinoko-geo", "nonaki", "hello-cookie", "sikika"
]
[extra.versions]
akurai = "4.3.2"
spinoko = "2.9.0"
sikika = "2.0.1"
fxt = "1.3.5"
kemoku = "2.2.0"
sibet = "2.1.0"
dinodds = "1.5.0"
akurai-geo = "2.0.0"
spinoko-geo = "1.1.4"
nonaki = "1.0.4"
hello-cookie = "1.0.2"

[extra.links]
website = "https://dinomatic.com"
telegram = "https://t.me/dinomatic"
github = "https://github.com/dinomatic"
wordpress_services = "https://dinomatic.com/web-development"
custom_cms = "https://dinomatic.com/gambling-cms"
